# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("1000x1000")
window.configure(bg="#ffffff")
window.title("Untitled")

canvas = tk.Canvas(
    window,
    bg = "#ffffff",
    width = 1000,
    height = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

button_1_image = tk.PhotoImage(file=load_asset("frame_1/1.png"))

button_1 = tk.Button(
    image=button_1_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 has been pressed!")
)

button_1.place(x=362, y=115, width=245, height=245)

button_2_image = tk.PhotoImage(file=load_asset("frame_1/2.png"))

button_2 = tk.Button(
    image=button_2_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 has been pressed!")
)

button_2.place(x=362, y=421, width=245, height=245)

button_3_image = tk.PhotoImage(file=load_asset("frame_1/3.png"))

button_3 = tk.Button(
    image=button_3_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 has been pressed!")
)

button_3.place(x=362, y=727, width=245, height=245)

image_1 = tk.PhotoImage(file=load_asset("logo.png"))

canvas.create_image(499, 42, image=image_1)

window.resizable(False, False)
window.mainloop()
